### PR TITLE
remove libz-dev from Ubuntu install_packages. It is already a listed pre...

### PR DESCRIPTION
**Pull request by ahayes**
It is already a listed pre...-req in the readme (by another name) and causes rake to need sudo privileges.

### CODE REVIEW

**Comment by jschneider** [comment]
This one drives me crazy: Every time I call rake, I have to enter the sudo password....

**Comment by ryancole** [comment]
This is still an issue with build-couchdb. Happening to me on a fresh Ubuntu 12.10 install.

**Comment by jhs** [comment]
@ryancole and all,

Does it work better now in the master branch? I have it using libz-dev for older Ubuntu but not for newer.

Thanks.

**Comment by jyg68** [comment]
Issue is still there for me, Ubuntu 12.10, zlib1g-dev installed:

<pre>
Build CouchDB commit: 862e8f50f2b779255847e2cba5c1be74505c1ca0
##
## Missing package: zlib1g-dev
##
## Try: sudo apt-get -y install zlib1g-dev
##
rake aborted!
Missing package: zlib1g-dev
</pre>

Blocking. Is there any turn-around? I tried to sudo the rake comment as suggested by jschneider, but this makes no difference.

Thanks

**Comment by ryancole** [comment]
You can get around it by simply removing the dependency check from the script, if you really need to. That's what I ended up doing.

**Comment by jhs** [comment]
That sounds like great bang/buck.

On Wed, Feb 20, 2013 at 12:10 AM, Ryan Cole notifications@github.comwrote:

> You can get around it by simply removing the dependency check from the
> script, if you really need to. That's what I ended up doing.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/iriscouch/build-couchdb/pull/54#issuecomment-13784411.

## 

Iris Couch

**Comment by ryancole** [comment]
I would test, but I moved on once I got it working. I will spin up a VM sometime this afternoon and try it out.

**Comment by jyg68** [comment]
Ok, thanks ryan, I removed the check from the tasks/all.rake

<pre> #install_packages(%w[ flex dctrl-tools libsctp-dev ed ] + [ libz_dev ]) </pre>

Then, been able to continue. Reached the error "Unable to find the `ax_check_icu.m4' file. Have you installed GNU Autoconf Archive?". But that is another thread.

**Comment by jeffreycharette** [comment]
+1 on my way to find `ax_check_icu.m4' file issue.

**Pull request closed without merging**
